# Generated by Django 3.2.8 on 2021-10-24 22:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('phone', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('Last_name', models.CharField(max_length=255)),
                ('Volunteer', models.BooleanField(default=True)),
                ('Picture', models.ImageField(default='User Profile Pic/default.png', upload_to='User Profile Pic/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Animal_Characteristics_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('characteristicsTag', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Animal_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Incident_After_Photos_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Volunteer_After_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_Before_Photos_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Volunteer_Before_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_Photos_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='Report_Images/')),
            ],
        ),
        migrations.CreateModel(
            name='SubAnimal_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subAnimal', models.CharField(max_length=400)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.animal_table')),
            ],
        ),
        migrations.CreateModel(
            name='Incident_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateTime', models.DateTimeField()),
                ('lat', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('lng', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('location', models.CharField(max_length=500)),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=18)),
                ('email', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subanimal_table')),
                ('characteristics', models.ManyToManyField(to='backend.Animal_Characteristics_Table')),
                ('photos', models.ManyToManyField(to='backend.Incident_Photos_Table')),
            ],
        ),
        migrations.CreateModel(
            name='Group_Incident_Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upLat', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('downLat', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('leftLng', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('rightLng', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('description', models.TextField()),
                ('procedureDone', models.TextField()),
                ('timeArrived', models.DateTimeField()),
                ('timeLeft', models.DateTimeField()),
                ('volunteerCheck', models.BooleanField(default=False)),
                ('incident', models.ManyToManyField(to='backend.Incident_Table')),
                ('pictureAfter', models.ManyToManyField(to='backend.Incident_After_Photos_Table')),
                ('pictureBefore', models.ManyToManyField(to='backend.Incident_Before_Photos_Table')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
