# Generated by Django 3.2.8 on 2021-10-27 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_tokenissued'),
    ]

    operations = [
        migrations.AddField(
            model_name='tokenissued',
            name='email',
            field=models.EmailField(default='now', max_length=225, unique=True),
            preserve_default=False,
        ),
    ]
