# Generated by Django 3.2.9 on 2021-11-07 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20211106_2126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='bottom',
            new_name='BottomLat',
        ),
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='left',
            new_name='LeftLng',
        ),
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='right',
            new_name='RightLng',
        ),
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='top',
            new_name='TopLat',
        ),
    ]
