# Generated by Django 3.2.9 on 2021-11-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20211106_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_incident_table',
            name='BottomLat',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='LeftLng',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='RightLng',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='TopLat',
            field=models.DecimalField(decimal_places=15, max_digits=19),
        ),
    ]
