# Generated by Django 3.2.8 on 2021-10-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_tokenissued_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenissued',
            name='email',
            field=models.EmailField(max_length=225),
        ),
    ]
