# Generated by Django 3.2.9 on 2021-11-07 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_auto_20211106_2223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='BottomLat',
            new_name='Bottom',
        ),
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='LeftLng',
            new_name='Left',
        ),
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='RightLng',
            new_name='Right',
        ),
        migrations.RenameField(
            model_name='group_incident_table',
            old_name='TopLat',
            new_name='Top',
        ),
    ]
