# Generated by Django 3.2.9 on 2021-11-07 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211106_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_incident_table',
            name='Animal_Present',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='BleachNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='CauseOfDeath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.death'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='FAST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.fast'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Hotline_Operator_Initials',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='How_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.how_id'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='ID_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='ID_Perm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='ID_Verified_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Molt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='MomPup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Responder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Responder_Arrived',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Responder_Left',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='SealLogging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='SealSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sealsize'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Seal_Depart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Seal_Depart_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Seal_Depart_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Tag_Color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tagcolor'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Tag_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Tag_Side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tagside'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Volunteers_Engaged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='Where_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='beach_Position',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='locationDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='onIsland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.island'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sex'),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.status'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Animal_Present',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='BleachNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='CauseOfDeath',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.death'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Delivered',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='FAST',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.fast'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='How_ID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.how_id'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='ID_Description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='ID_Perm',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Molt',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='MomPup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Responder',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Responder_Arrived',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Responder_Left',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='SRA_Set_Up',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='SRA_Set_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='SealLogging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='SealSize',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sealsize'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Seal_Depart',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Seal_Depart_Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Seal_Depart_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Tag_Color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tagcolor'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Tag_Number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Tag_Side',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.tagside'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Volunteers_Engaged',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='Where_To',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.location'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='beach_Position',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='locationDetails',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='onIsland',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.island'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.sex'),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='incident_table',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='backend.status'),
        ),
    ]
