# Generated by Django 3.2.8 on 2021-10-29 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_auto_20211028_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal_characteristics_table',
            name='characteristicsTag',
            field=models.CharField(max_length=400, unique=True),
        ),
    ]
