# Generated by Django 3.2.9 on 2021-11-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_auto_20211107_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group_incident_table',
            name='SRA_Set_Up',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='SRA_Set_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
