# Generated by Django 3.2.8 on 2021-10-29 09:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_incident_table_people'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ParentAndChildPair', models.BooleanField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subanimal_table')),
                ('characteristics', models.ManyToManyField(to='backend.Animal_Characteristics_Table')),
            ],
        ),
        migrations.RemoveField(
            model_name='group_incident_table',
            name='pictureAfter',
        ),
        migrations.RemoveField(
            model_name='group_incident_table',
            name='pictureBefore',
        ),
        migrations.RemoveField(
            model_name='group_incident_table',
            name='procedureDone',
        ),
        migrations.RemoveField(
            model_name='group_incident_table',
            name='timeArrived',
        ),
        migrations.RemoveField(
            model_name='group_incident_table',
            name='timeLeft',
        ),
        migrations.RemoveField(
            model_name='incident_table',
            name='animal',
        ),
        migrations.RemoveField(
            model_name='incident_table',
            name='characteristics',
        ),
        migrations.AddField(
            model_name='group_incident_table',
            name='amountOfAnimal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='incident_table',
            name='amountOfAnimals',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group_incident_table',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Volunteer_Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure', models.DateTimeField(blank=True)),
                ('departureInfo', models.TextField(blank=True)),
                ('ParentAndChildPair', models.BooleanField()),
                ('timeArrived', models.DateTimeField()),
                ('timeLeft', models.DateTimeField()),
                ('description', models.TextField()),
                ('humanInteraction', models.TextField()),
                ('procedureDone', models.TextField()),
                ('bleachedToday', models.BooleanField(blank=True)),
                ('lat', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('lng', models.DecimalField(db_index=True, decimal_places=15, max_digits=19)),
                ('Temps', models.DecimalField(db_index=True, decimal_places=2, max_digits=8)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subanimal_table')),
                ('animalReport', models.ManyToManyField(to='backend.ReportedAnimal')),
                ('pictureAfter', models.ManyToManyField(to='backend.Incident_After_Photos_Table')),
                ('pictureBefore', models.ManyToManyField(to='backend.Incident_Before_Photos_Table')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='group_incident_table',
            name='volunteerReport',
            field=models.ManyToManyField(to='backend.Volunteer_Report'),
        ),
        migrations.AddField(
            model_name='incident_table',
            name='animalsInIncident',
            field=models.ManyToManyField(to='backend.ReportedAnimal'),
        ),
    ]
